webserver:
  port: 3000
  apiPort: 3001

# Google Analytics key
ga: "UA-XXXXX-X"

logger:
  # Log Levels:
  # SEVERE: 1000
  # WARN:   800
  # INFO:   600
  # FINE:   400
  # FINER:  200
  # FINEST: 100
  level: 100
  syslog: false
  file: false
  console: true
  filename: "./logs/app.log"

mongo:
  user: "user"
  password: ""
  hostname: "alex.mongohq.com:10083"
  database: "ibeacon"
  uri: "mongodb://user:@alex.mongohq.com:10083/ibeacon"
  # Attempt to reconnect interval in ms.
  reconnectTime: 500

echoServer: "http://localhost"
webserverUrl: "http://localhost:3000"
