webserver:
  port: 80

# Google Analytics key
ga: "UA-xxxx-2"

logger:
  # Log Levels:
  # SEVERE: 1000
  # WARN:   800
  # INFO:   600
  # FINE:   400
  # FINER:  200
  # FINEST: 100
  level: 100
  syslog: false
  file: false
  console: true
  filename: "./logs/app.log"

mongo:
  user: ""
  pass: ""
  uri: ""

webserverUrl: "http://store.com"
