webserver:
  port: 80

# Google Analytics key
ga: "UA-xxxxxx-2"

logger:
  # Log Levels:
  # SEVERE: 1000
  # WARN:   800
  # INFO:   600
  # FINE:   400
  # FINER:  200
  # FINEST: 100
  level: 100
  syslog: false
  file: false
  console: true
  filename: "./logs/app.log"

mongo:
  user: "ccuser"
  pass: ""
  uri: "mongodb://ccuser:@paulo.mongohq.com:10092/cc"

echoServer: "ibeacon-store.herokuapp.com"
webserverUrl: "http://check-connectivity.com"
